### PR TITLE
Added YAML and CSV files - Bureaufax Table

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
Hi Ron,
I have pushed yaml and csv files for Algeria in order to get some feedback from you. Then, I will continue with the rest.
Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 I've updated the Algeria YAML file and also added two sample files to follow. Hope this works!

**Comment by manuelfuenmayor** [comment]
Hi @ronaldtse ,
I have pushed the YAML and CSV files for the rest of the countries.
For the countries that contain both part3 and part4, I put their contents in the same CSV file, separated by a blank line.
I'll be aware of your corrections. 
Thanks!

**Comment by manuelfuenmayor** [comment]
By the way, could you please take a look at Congo country? I have some doubts about it.
Here's the source doc (page 13): 
[Cameroun - Cuba (docx).docx](https://github.com/ituob/service-publications-data/files/3995234/Cameroun.-.Cuba.docx.docx)

**Comment by ronaldtse** [comment]
@manuel489 sorry for the delay -- is the question about the footnotes?

Screen Shot 2020-03-01 at 10 22 00 AM

**Comment by manuelfuenmayor** [comment]
Hi @ronaldtse ,
> is the question about the footnotes?

No, I mean, it's about the encoding of the *Congo* country:

capture-congo
 
As shown above, it contains several contact directions, faxes, etc... So, I encoded it like this:
````
# CONGO
country_name:
  en: CONGO
  fr: CONGO
  es: CONGO

type:
  - FAX-EXPRESS
  - POSTE

contact: 
    - |
    Direction générale de l'Office National des Postes et Télécommunications (ONPT)
    BRAZZAVILLE
    CONGO
    
    - |
    Direction des Télécommunications 
    ONPT
    Brazzaville
    
    - |
    Direction des Postes
    ONPT
    Brazzaville

tg: 
  - Ofipostel Brazzaville
  - Dirtel Brazzaville
  
tlx: Ofipostel 5470 KG

fax: 
  - +242 810752
  - +242 810024
  - +242 813464
  
gr: 
  - 3
  - 3
  - 3
  
tf: 
  - +242 810998
  - +242 815999
  - +242 815591

part2:
  col_c: true
  col_d: true
  col_e: true
  col_f: true
````

And I was wondering if that is correct...

**Comment by ronaldtse** [comment]
Yes this is mostly good, except that you need one more indent for the text after `- |`.

e.g. bad:
```yaml
contact: 
    - |
    Direction générale de l'Office National des Postes et Télécommunications (ONPT)
    BRAZZAVILLE
    CONGO
```

good:

```yaml
contact: 
    - |
      Direction générale de l'Office National des Postes et Télécommunications (ONPT)
      BRAZZAVILLE
      CONGO
```

**Comment by manuelfuenmayor** [comment]
Ok, thanks @ronaldtse. I have fixed it.

**Comment by ronaldtse** [comment]
Thanks @manuel489 !

**Pull request merged**
