### PR TITLE
Added ROA lists in Excel/Word format

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
Hi Ron,

I have gathered the ROA lists into Excel and Word files; i.e some countries are in Excel format, and some others, in Word format. The reason for this, is because there were cases where the doc/docx file was available for direct download.

However, there are several countries that don't show any ROA list but a link to a website. These countries are:

- Austria: https://www.itu.int/oth/T020400000E/en
- Belgium: https://www.itu.int/oth/T0204000015/en
- France: https://www.itu.int/oth/T0204000048/en
- Germany: https://www.itu.int/oth/T020400004E/en
- Gibraltar: https://www.itu.int/oth/T0204000050/en
- India: https://www.itu.int/oth/T020400005F/en
- Liechtenstein: https://www.itu.int/oth/T0204000075/en
- Portugal: https://www.itu.int/oth/T02040000A2/en
- Sri Lanka: https://www.itu.int/oth/T02040000BD/en
- Switzerland: https://www.itu.int/oth/T02040000C2/en
- Turkey: https://www.itu.int/oth/T02040000CE/en

(Some links don't work.)
I didn't include such links in this PR. Let me know if I have to.

Besides, there are two countries that don't show any information at all. These are:
- Guinea-Bissau: https://www.itu.int/oth/T0204000058/en
- Papua New Guinea: https://www.itu.int/oth/T020400009D/en

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 could you help convert these to CSV formats according to these columns via Excel? Thanks!

[Afganistan.csv.zip](https://github.com/ituob/service-publications-data/files/3937466/Afganistan.csv.zip)

**Comment by manuelfuenmayor** [comment]
Hi @ronaldtse  !
CSV files created. I put them in a separated folder.
Also, I added a `URL` column. So, the final set of columns is:
`Name, Address, Tel, Fax, Email, URL, OB`
Please, let me know if I should make corrections.
Thanks!

**Comment by ronaldtse** [comment]
@manuel489 for the Word and Excel files, can you upload to the https://github.com/ituob/service-publications-refs/ repository? In this current repo, we only need the CSV files. Thanks!

**Comment by manuelfuenmayor** [comment]
Excel and Word files moved to https://github.com/ituob/service-publications-refs/pull/4

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
